bot:
  guild_id: "615264378014531724"
  console_channel: "691362207300321381"
  errors_channel: "691362207300321381"
  log_channel: "691362207300321381"
  templates: ./assets/templates/
cache:
  path: ./cache/
  ttl:
    blank: 5m
    username: 30s
storage:
  connection: postgresql://bot:password@localhost:54320/anihouse?sslmode=disable
  driver: pgx
  max_idle_connection: 3
  max_open_connection: 2
  log:
    file: ./logs/storage.log
    level: trace
    formatter: json
modules:
  awards:
    config: ./config/dev/modules/awards.yaml
    enabled: false
    prefix: "-"
    log:
      file: ./logs/awards.log
      level: trace
      formatter: text
  xp:
    config: ./config/dev/modules/xp.yaml
    enabled: false
    prefix: "-"
    log:
      file: ./logs/xp.log
      level: trace
      formatter: text
  triggers:
    enabled: false
    prefix: "-"
    log:
      file: ./logs/triggers.log
      level: trace
      formatter: text
  clubs:
    enabled: true
    prefix: "-"
    log:
      file: ./logs/clubs.log
      level: trace
      formatter: text
session: {}