bot:
  guild_id: "615264378014531724"
  console_channel: "691362207300321381"
  errors_channel: "691362207300321381"
  log_channel: "691362207300321381"
  templates: ./assets/templates/
cache:
  path: ./cache/
  ttl:
    blank: 5m
    username: 30s
modules:
  awards:
    config: ./config/dev/modules/awards.yaml
    enabled: false
    prefix: "-"
  xp:
    config: ./config/dev/modules/xp.yaml
    enabled: false
    prefix: "-"
  triggers:
    enabled: true
    prefix: "-"
session: {}
storage:
  connection: password=vanilla
  driver: postgres
