session:
  log:
    file: ./logs/session.log
    level: info
    formatter: text
bot:
  guild_id: "615264378014531724"
  channels:
    console: "691362207300321381"
    errors: "691362207300321381"
    logs: "691362207300321381"
  templates: ./assets/templates/
  log:
    file: ./logs/bot.log
    level: trace
    formatter: text
cache:
  path: ./cache/
  ttl:
    blank: 5m
    username: 30s
storage:
  connection: postgresql://admin:admin@localhost:54320/bot?sslmode=disable
  driver: pgx
  max_idle_connection: 3
  max_open_connection: 2
  log:
    file: ./logs/storage.log
    level: trace
    formatter: text
modules:
  awards:
    config: ./modules/awards.yaml
    enabled: false
    prefix: "-"
    log:
      file: ./logs/awards.log
      level: trace
      formatter: text
  xp:
    config: ./modules/xp.yaml
    enabled: false
    prefix: "-"
    log:
      file: ./logs/xp.log
      level: trace
      formatter: text
  triggers:
    enabled: false
    prefix: "-"
    log:
      file: ./logs/triggers.log
      level: trace
      formatter: text
  clubs:
    enabled: true
    prefix: "-"
    config: ./modules/clubs.yaml
    log:
      file: ./logs/clubs.log
      level: trace
      formatter: text